name: Sync Docs to `docs/`

on:
  push:
    branches: [main]

jobs:
  copy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare docs structure
        run: |
          mkdir -p docs
          mkdir -p docs/changelog
          mkdir -p docs/contributing
          mkdir -p docs/license

      - name: Copy and wrap README.md to docs/index.md
        run: |
          echo "---" > docs/index.md
          echo "title: Головна" >> docs/index.md
          echo "---" >> docs/index.md
          cat README.md >> docs/index.md

      - name: Copy and wrap CHANGELOG.md to docs/changelog/index.md
        run: |
          echo "---" > docs/changelog/index.md
          echo "title: Зміни" >> docs/changelog/index.md
          echo "---" >> docs/changelog/index.md
          cat CHANGELOG.md >> docs/changelog/index.md

      - name: Copy and wrap LICENSE to docs/license/index.md
        run: |
          echo "---" > docs/license/index.md
          echo "title: Ліцензія" >> docs/license/index.md
          echo "---" >> docs/license/index.md
          cat LICENSE >> docs/license/index.md

      - name: Copy and wrap CONTRIBUTING.md to docs/contributing/index.md
        run: |
          echo "---" > docs/contributing/index.md
          echo "title: Як допомогти" >> docs/contributing/index.md
          echo "---" >> docs/contributing/index.md
          cat CONTRIBUTING.md >> docs/contributing/index.md

      - name: Commit and push if docs changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update docs from root files"
            git push
          fi

